#!/usr/bin/env python3
"""gen_eeprom_img.py - build eeprom_img.h for pio-ftdi QUAD mode.

128-word FT4232H image in the layout AMD's program_ftdi writes
(verified word-for-word against a harvested AMD write, 2026-08-24):

  0x00-0x0B  config (words 8,9 verbatim from the AMD write)
  0x0C       0x0056 header
  0x0D-0x0E  signature 0x0004 0x584A
  0x0F..     vendor"\\0"board"\\0" UTF-8, 2 bytes/word lo-first
  0x4D..     string blocks chained: marker (0x03<<8|len) + 1 word/char
             (manufacturer, product, serial, empty terminator 0x0302)
  0x7F       checksum: cs=0xAAAA; cs=rol16(cs^w,1) over words 0..0x7E
             (intra2net libftdi src/ftdi.c; verified on 2 harvested images)

Self-test: serial PIOJTAG002 must reproduce tools/testdata/eeprom_amd_write_002.txt
(a captured AMD program_ftdi write of this exact persona) word for word.
"""
import sys

VENDOR = sys.argv[1] if len(sys.argv) > 1 else "pio-ftdi"
BOARD = sys.argv[2] if len(sys.argv) > 2 else "PIO-JTAG-01 FT4232H"
PRODUCT = sys.argv[3] if len(sys.argv) > 3 else "pio-ftdi JTAG adapter"
SERIAL = sys.argv[4] if len(sys.argv) > 4 else "PIOJTAG000"
MFR = "Xilinx"          # required by hw_server (AMD's own scripts write this)

def rol16(x): return ((x << 1) | (x >> 15)) & 0xFFFF

w = [0x0000] * 128
w[0x00:0x0C] = [0x8880, 0x0403, 0x6011, 0x0800, 0x3280, 0x0008,
                0x0000, 0x0e9a, 0x2ca8, 0x16d4, 0x0000, 0x0000]

w[0x0C] = 0x0056
w[0x0D] = 0x0004
w[0x0E] = 0x584A
b = (VENDOR + "\0" + BOARD + "\0").encode()
if len(b) & 1: b += b"\0"
for i in range(0, len(b), 2):
    w[0x0F + i // 2] = b[i] | (b[i + 1] << 8)

def block(s):
    return [(0x03 << 8) | (2 + 2 * len(s))] + list(s.encode())

blocks = block(MFR) + block(PRODUCT) + block(SERIAL) + [0x0302]
assert 0x4D + len(blocks) <= 0x7F, "string blocks overflow the image"
w[0x4D:0x4D + len(blocks)] = blocks

cs = 0xAAAA
for x in w[:0x7F]:
    cs = rol16(cs ^ x)
w[0x7F] = cs

if SERIAL == "PIOJTAG002":
    import os
    ref_path = os.path.join(os.path.dirname(__file__), "testdata", "eeprom_amd_write_002.txt")
    try:
        ref = [int(x, 16) for x in open(ref_path).read().split()]
        bad = [i for i in range(128) if w[i] != ref[i]]
        print("SELF-TEST: %s" % ("PASS 128/128" if not bad else "FAIL at %s" % bad))
        sys.exit(0 if not bad else 1)
    except OSError:
        print("SELF-TEST skipped (no reference file)")

out = ["// eeprom_img.h - GENERATED by gen_eeprom_img.py; do not edit by hand.",
       "static const uint16_t eeprom_img[128] = {"]
for i in range(0, 128, 8):
    out.append("    " + ", ".join("0x%04x" % x for x in w[i:i + 8]) + ",")
out += ["};", ""]
open("src/eeprom_img.h", "w").write("\n".join(out))
print("vendor=%r board=%r product=%r serial=%r cs=0x%04x" % (VENDOR, BOARD, PRODUCT, SERIAL, cs))
